services:
  monitor-slots:
    build:
      context: .
      dockerfile: test-app/Dockerfile
      args:
        MONITOR: monitor-slots
    env_file: test-app/.env
    restart: unless-stopped

  monitor-transactions:
    build:
      context: .
      dockerfile: test-app/Dockerfile
      args:
        MONITOR: monitor-transactions
    env_file: test-app/.env
    restart: unless-stopped

  monitor-blocks:
    build:
      context: .
      dockerfile: test-app/Dockerfile
      args:
        MONITOR: monitor-blocks
    env_file: test-app/.env
    restart: unless-stopped

  monitor-accounts:
    build:
      context: .
      dockerfile: test-app/Dockerfile
      args:
        MONITOR: monitor-accounts
    env_file: test-app/.env
    restart: unless-stopped
